#!/usr/bin/env bash
# vim: ft=sh

#What do we need to check for:
##Vagrant installed
##Vagrant Cashier
##VirtalBox installed
##Ansible installed

SUBCOMMAND_DESC="Verifique o setup do projeto"
SUBCOMMAND_HELP=$(cat <<EOH
Usage ${MAIN_COMMAND} ${SUBCOMMAND} [check] [install]

check TODO!
install TODO!

EOH
)

function check_setup()
{
  echo "check setup was called"
}

function install_dependencies()
{
  echo "install all was called"
}

is_help_mode "${@}" && return

#Different actions based on arguments
case ${1} in
  check)
    check_setup
    ;;
  install)
    install_dependencies
  ;;
esac
